import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "@/lib/react-query-provider";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "@/context/auth";

export const metadata: Metadata = {
  title: "Anka Tech",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark">
      <body>
        <ReactQueryProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
          <ToastContainer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
